## Settings
title: root
owner: shreybs
url: "https://shreybs.github.io"
baseurl: 
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "shreyas.belv@gmail.com"
github: "shreybs/"

statement: "There Is No Spoon."
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθ4ικλμνξοπρστυ2φχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
